#!/usr/bin/env bash
# Install and configure HAProxy as a load balancer

apt-get update
apt-get install -y haproxy

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

cat > /etc/haproxy/haproxy.cfg << 'HAPROXY_EOF'
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 7050-web-01 44.201.182.188:80 check
HAPROXY_EOF

sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

service haproxy restart
